version: "3.8"

services:
  web:
    user: root
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/
    volumes:
      - .:/rails
    # command: bash -c "bundle config set without 'production' && bundle install && bundle exec rails server -b 0.0.0.0"
