version: "3.8"

services:
  web:
    user: root
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/
    volumes:
      - .:/rails
